<#
.SYNOPSIS
Validates the identifier proposal worksheet and produces an MQG-02 completion preflight report.

.DESCRIPTION
Reads the identifier proposal worksheet generated by New-IdentifierProposalWorksheet.ps1
and validates whether each row is structurally safe for future MQG-02 completion.

This script is read-only and does not modify Calibre metadata.

It does not mark MQG-02 complete. It only classifies rows as:
- Ready - MQG-02 Completion Preflight
- Manual Review Required
- Blocked - Validation Error

.EXAMPLE
powershell -ExecutionPolicy Bypass -File .\scripts\Test-IdentifierProposalWorksheet.ps1 `
  -ProposalTsv ".\input\identifier-proposal-worksheet.tsv" `
  -ValidationCsv ".\reports\identifier-proposal-validation.csv" `
  -ValidationSummaryCsv ".\reports\identifier-proposal-validation-summary.csv"
#>

[CmdletBinding()]
param(
    [string]$ProposalTsv = ".\input\identifier-proposal-worksheet.tsv",

    [string]$ValidationCsv = ".\reports\identifier-proposal-validation.csv",

    [string]$ValidationSummaryCsv = ".\reports\identifier-proposal-validation-summary.csv"
)

function Get-RowValue {
    param(
        [Parameter(Mandatory = $true)]
        [object]$Row,

        [Parameter(Mandatory = $true)]
        [string]$Name
    )

    $property = $Row.PSObject.Properties[$Name]

    if ($null -eq $property) {
        return ""
    }

    return ([string]$property.Value).Trim()
}

function Test-YesNo {
    param(
        [AllowNull()]
        [string]$Value
    )

    return $Value -in @("Yes", "No")
}

function Test-NonBlank {
    param(
        [AllowNull()]
        [string]$Value
    )

    return -not [string]::IsNullOrWhiteSpace($Value)
}

function Convert-ToIntSafe {
    param(
        [AllowNull()]
        [string]$Value
    )

    $number = 0

    if ([int]::TryParse($Value, [ref]$number)) {
        return $number
    }

    return $null
}

if (-not (Test-Path $ProposalTsv)) {
    throw "Proposal TSV not found: $ProposalTsv"
}

Write-Host "Identifier proposal worksheet validation"
Write-Host "========================================"
Write-Host ""
Write-Host "This operation is read-only and does not modify Calibre metadata."
Write-Host "Proposal TSV: $ProposalTsv"
Write-Host "Validation CSV: $ValidationCsv"
Write-Host "Validation summary CSV: $ValidationSummaryCsv"
Write-Host ""

$rows = @(Import-Csv -Path $ProposalTsv -Delimiter "`t")

if ($rows.Count -eq 0) {
    throw "Proposal TSV has no rows: $ProposalTsv"
}

$requiredColumns = @(
    "CalibreId",
    "Title",
    "Authors",
    "RecommendedStatus",
    "ProposedAction",
    "ApprovalStatus",
    "ManualReviewRequired",
    "Confidence",
    "Mqg02CompletionCandidate",
    "ExistingIsbn",
    "ExistingAmazonOrAsin",
    "ExistingGoodreads",
    "HasSuspiciousType",
    "HasDuplicateIsbn",
    "HasDuplicateAmazon",
    "HasDuplicateGoodreads",
    "IssueCount",
    "IssueSummary"
)

$availableColumns = @($rows[0].PSObject.Properties.Name)
$missingColumns = @($requiredColumns | Where-Object { $_ -notin $availableColumns })

if ($missingColumns.Count -gt 0) {
    throw "Proposal TSV is missing required columns: $($missingColumns -join ', ')"
}

$allowedApprovalStatuses = @(
    "Proposed - Auto Eligible",
    "Proposed - Needs Human Review",
    "Approved",
    "Rejected",
    "Accepted As-Is",
    "Do Not Apply"
)

$allowedProposedActions = @(
    "Accept As-Is",
    "Research Missing ISBN",
    "Review Missing External Link Targets",
    "Review Missing One External Link Target",
    "Review Duplicate Identifier",
    "Review Suspicious Identifier Type",
    "Flag Review"
)

$allowedConfidenceValues = @(
    "High",
    "Medium",
    "Low"
)

$idCounts = @{}

foreach ($row in $rows) {
    $calibreId = Get-RowValue -Row $row -Name "CalibreId"

    if (Test-NonBlank $calibreId) {
        if (-not $idCounts.ContainsKey($calibreId)) {
            $idCounts[$calibreId] = 0
        }

        $idCounts[$calibreId]++
    }
}

$validationRows = foreach ($row in $rows) {
    $issues = @()

    $calibreId = Get-RowValue -Row $row -Name "CalibreId"
    $title = Get-RowValue -Row $row -Name "Title"
    $authors = Get-RowValue -Row $row -Name "Authors"
    $recommendedStatus = Get-RowValue -Row $row -Name "RecommendedStatus"
    $proposedAction = Get-RowValue -Row $row -Name "ProposedAction"
    $approvalStatus = Get-RowValue -Row $row -Name "ApprovalStatus"
    $manualReviewRequired = Get-RowValue -Row $row -Name "ManualReviewRequired"
    $confidence = Get-RowValue -Row $row -Name "Confidence"
    $mqg02CompletionCandidate = Get-RowValue -Row $row -Name "Mqg02CompletionCandidate"
    $existingIsbn = Get-RowValue -Row $row -Name "ExistingIsbn"
    $existingAmazonOrAsin = Get-RowValue -Row $row -Name "ExistingAmazonOrAsin"
    $existingGoodreads = Get-RowValue -Row $row -Name "ExistingGoodreads"
    $hasSuspiciousType = Get-RowValue -Row $row -Name "HasSuspiciousType"
    $hasDuplicateIsbn = Get-RowValue -Row $row -Name "HasDuplicateIsbn"
    $hasDuplicateAmazon = Get-RowValue -Row $row -Name "HasDuplicateAmazon"
    $hasDuplicateGoodreads = Get-RowValue -Row $row -Name "HasDuplicateGoodreads"
    $issueCountText = Get-RowValue -Row $row -Name "IssueCount"
    $issueCount = Convert-ToIntSafe -Value $issueCountText

    if (-not (Test-NonBlank $calibreId)) {
        $issues += "Missing CalibreId"
    }
    elseif ($idCounts[$calibreId] -gt 1) {
        $issues += "Duplicate CalibreId in proposal worksheet"
    }

    if (-not (Test-NonBlank $title)) {
        $issues += "Missing title"
    }

    if (-not (Test-NonBlank $authors)) {
        $issues += "Missing authors"
    }

    if ($approvalStatus -notin $allowedApprovalStatuses) {
        $issues += "Unexpected ApprovalStatus: $approvalStatus"
    }

    if ($proposedAction -notin $allowedProposedActions) {
        $issues += "Unexpected ProposedAction: $proposedAction"
    }

    if ($confidence -notin $allowedConfidenceValues) {
        $issues += "Unexpected Confidence: $confidence"
    }

    if (-not (Test-YesNo $manualReviewRequired)) {
        $issues += "ManualReviewRequired must be Yes or No"
    }

    if (-not (Test-YesNo $mqg02CompletionCandidate)) {
        $issues += "Mqg02CompletionCandidate must be Yes or No"
    }

    foreach ($flagName in @("HasSuspiciousType", "HasDuplicateIsbn", "HasDuplicateAmazon", "HasDuplicateGoodreads")) {
        $flagValue = Get-RowValue -Row $row -Name $flagName

        if (-not (Test-YesNo $flagValue)) {
            $issues += "$flagName must be Yes or No"
        }
    }

    if ($null -eq $issueCount) {
        $issues += "IssueCount is not numeric"
        $issueCount = -1
    }

    $coreReadyCriteriaMet = (
        $recommendedStatus -eq "Ready - Strong Core" -and
        $proposedAction -eq "Accept As-Is" -and
        $approvalStatus -eq "Proposed - Auto Eligible" -and
        $manualReviewRequired -eq "No" -and
        $confidence -eq "High" -and
        $mqg02CompletionCandidate -eq "Yes" -and
        (Test-NonBlank $existingIsbn) -and
        (Test-NonBlank $existingAmazonOrAsin) -and
        (Test-NonBlank $existingGoodreads) -and
        $hasSuspiciousType -eq "No" -and
        $hasDuplicateIsbn -eq "No" -and
        $hasDuplicateAmazon -eq "No" -and
        $hasDuplicateGoodreads -eq "No" -and
        $issueCount -eq 0
    )

    if ($mqg02CompletionCandidate -eq "Yes" -and -not $coreReadyCriteriaMet) {
        $issues += "MQG-02 completion candidate does not meet strong-core readiness criteria"
    }

    if ($approvalStatus -eq "Proposed - Auto Eligible" -and $manualReviewRequired -ne "No") {
        $issues += "Auto-eligible proposal requires ManualReviewRequired = No"
    }

    if ($approvalStatus -eq "Proposed - Needs Human Review" -and $manualReviewRequired -ne "Yes") {
        $issues += "Human-review proposal requires ManualReviewRequired = Yes"
    }

    $validationStatus = "Manual Review Required"
    $completionPreflightEligible = "No"
    $validationBasis = "Proposal requires human review before MQG-02 completion."

    if ($issues.Count -gt 0) {
        $validationStatus = "Blocked - Validation Error"
        $completionPreflightEligible = "No"
        $validationBasis = "Proposal row failed structural or readiness validation."
    }
    elseif ($coreReadyCriteriaMet) {
        $validationStatus = "Ready - MQG-02 Completion Preflight"
        $completionPreflightEligible = "Yes"
        $validationBasis = "Proposal row satisfies strong-core identifier criteria and is ready for future MQG-02 completion preflight."
    }

    [pscustomobject]@{
        CalibreId                    = $calibreId
        Title                        = $title
        Authors                      = $authors
        RecommendedStatus            = $recommendedStatus
        ProposedAction               = $proposedAction
        ApprovalStatus               = $approvalStatus
        ManualReviewRequired         = $manualReviewRequired
        Confidence                   = $confidence
        Mqg02CompletionCandidate     = $mqg02CompletionCandidate
        CompletionPreflightEligible  = $completionPreflightEligible
        ValidationStatus             = $validationStatus
        ValidationIssueCount         = $issues.Count
        ValidationIssues             = ($issues -join "; ")
        ValidationBasis              = $validationBasis
        ExistingIsbn                 = $existingIsbn
        ExistingAmazonOrAsin         = $existingAmazonOrAsin
        ExistingGoodreads            = $existingGoodreads
        HasSuspiciousType            = $hasSuspiciousType
        HasDuplicateIsbn             = $hasDuplicateIsbn
        HasDuplicateAmazon           = $hasDuplicateAmazon
        HasDuplicateGoodreads        = $hasDuplicateGoodreads
        IssueCount                   = $issueCount
        IssueSummary                 = Get-RowValue -Row $row -Name "IssueSummary"
        IdentifierTypes              = Get-RowValue -Row $row -Name "IdentifierTypes"
        IdentifiersRaw               = Get-RowValue -Row $row -Name "IdentifiersRaw"
    }
}

$summaryRows = @()

$summaryRows += $validationRows |
    Group-Object ValidationStatus |
    Sort-Object -Property @{ Expression = "Count"; Descending = $true }, @{ Expression = "Name"; Ascending = $true } |
    ForEach-Object {
        [pscustomobject]@{
            Metric = "ValidationStatus"
            Name   = $_.Name
            Count  = $_.Count
        }
    }

$summaryRows += $validationRows |
    Group-Object CompletionPreflightEligible |
    Sort-Object -Property @{ Expression = "Count"; Descending = $true }, @{ Expression = "Name"; Ascending = $true } |
    ForEach-Object {
        [pscustomobject]@{
            Metric = "CompletionPreflightEligible"
            Name   = $_.Name
            Count  = $_.Count
        }
    }

$summaryRows += $validationRows |
    Group-Object ProposedAction |
    Sort-Object -Property @{ Expression = "Count"; Descending = $true }, @{ Expression = "Name"; Ascending = $true } |
    ForEach-Object {
        [pscustomobject]@{
            Metric = "ProposedAction"
            Name   = $_.Name
            Count  = $_.Count
        }
    }

$outputFolders = @(
    (Split-Path -Path $ValidationCsv -Parent),
    (Split-Path -Path $ValidationSummaryCsv -Parent)
) | Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | Select-Object -Unique

foreach ($folder in $outputFolders) {
    if (-not (Test-Path $folder)) {
        New-Item -ItemType Directory -Force -Path $folder | Out-Null
    }
}

$validationRows | Export-Csv -Path $ValidationCsv -NoTypeInformation -Encoding UTF8
$summaryRows | Export-Csv -Path $ValidationSummaryCsv -NoTypeInformation -Encoding UTF8

$readyCount = @($validationRows | Where-Object { $_.ValidationStatus -eq "Ready - MQG-02 Completion Preflight" }).Count
$manualReviewCount = @($validationRows | Where-Object { $_.ValidationStatus -eq "Manual Review Required" }).Count
$blockedCount = @($validationRows | Where-Object { $_.ValidationStatus -eq "Blocked - Validation Error" }).Count

Write-Host "Proposal worksheet validation complete."
Write-Host "Rows reviewed: $($validationRows.Count)"
Write-Host "Ready for MQG-02 completion preflight: $readyCount"
Write-Host "Manual review required: $manualReviewCount"
Write-Host "Blocked / validation error: $blockedCount"
Write-Host ""
Write-Host "Files written:"
Write-Host "  $ValidationCsv"
Write-Host "  $ValidationSummaryCsv"
