<#
.SYNOPSIS
Writes a concise summary report for a Calibre LCC dry-run or verification CSV.

.DESCRIPTION
Reads a report generated by Test-LccImportDryRun.ps1 and writes a human-readable
summary text file showing match counts, pending update counts, warnings, audit
field counts, and final batch status.

This script does not modify Calibre metadata.

.EXAMPLE
powershell -ExecutionPolicy Bypass -File .\scripts\Write-LccBatchSummary.ps1 `
  -ReportCsv ".\reports\lcc-dryrun-herbert-baxter-adams-v02-test.csv" `
  -SummaryTxt ".\reports\lcc-summary-herbert-baxter-adams-v02-test.txt" `
  -BatchName "herbert-baxter-adams-v02-test"
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$ReportCsv,

    [string]$SummaryTxt = "",

    [string]$BatchName = "",

    [string]$ConfigPath = ".\config\lcc-toolkit.config.json"
)

function Get-ToolkitRoot {
    $scriptFolder = Split-Path -Parent $PSCommandPath
    return Split-Path -Parent $scriptFolder
}

function Resolve-ToolkitPath {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,

        [Parameter(Mandatory = $true)]
        [string]$ToolkitRoot
    )

    if ([System.IO.Path]::IsPathRooted($Path)) {
        return $Path
    }

    return Join-Path $ToolkitRoot $Path
}

function Count-Where {
    param(
        [Parameter(Mandatory = $true)]
        [object[]]$Rows,

        [Parameter(Mandatory = $true)]
        [scriptblock]$Predicate
    )

    return @($Rows | Where-Object $Predicate).Count
}

function Add-Line {
    param(
        [System.Collections.Generic.List[string]]$Lines,

        [string]$Text = ""
    )

    $Lines.Add($Text) | Out-Null
}

function Test-ColumnExists {
    param(
        [Parameter(Mandatory = $true)]
        [object]$Row,

        [Parameter(Mandatory = $true)]
        [string]$ColumnName
    )

    return ($Row.PSObject.Properties.Name -contains $ColumnName)
}

function Get-RowValue {
    param(
        [Parameter(Mandatory = $true)]
        [object]$Row,

        [Parameter(Mandatory = $true)]
        [string[]]$Names
    )

    foreach ($name in $Names) {
        $property = $Row.PSObject.Properties[$name]

        if ($null -ne $property) {
            return [string]$property.Value
        }
    }

    return ""
}

function Normalize-DisplayValue {
    param(
        [AllowNull()]
        [string]$Value,

        [string]$BlankLabel = "Unspecified"
    )

    if ([string]::IsNullOrWhiteSpace($Value)) {
        return $BlankLabel
    }

    return (($Value.Trim()) -replace '\s+', ' ')
}

$toolkitRoot = Get-ToolkitRoot

$configFullPath = Resolve-ToolkitPath -Path $ConfigPath -ToolkitRoot $toolkitRoot

if (Test-Path $configFullPath) {
    $config = Get-Content $configFullPath -Raw | ConvertFrom-Json
}
else {
    $config = $null
}

$reportFullPath = Resolve-ToolkitPath -Path $ReportCsv -ToolkitRoot $toolkitRoot

if (-not (Test-Path $reportFullPath)) {
    throw "Report CSV not found: $reportFullPath"
}

$rows = @(Import-Csv $reportFullPath)

if ($rows.Count -eq 0) {
    throw "Report CSV contains no rows: $reportFullPath"
}

if ([string]::IsNullOrWhiteSpace($BatchName)) {
    $BatchName = [System.IO.Path]::GetFileNameWithoutExtension($reportFullPath)
}

if ([string]::IsNullOrWhiteSpace($SummaryTxt)) {
    if ($null -ne $config -and -not [string]::IsNullOrWhiteSpace($config.ReportsFolder)) {
        $reportsFolder = Resolve-ToolkitPath -Path $config.ReportsFolder -ToolkitRoot $toolkitRoot
    }
    else {
        $reportsFolder = Split-Path -Parent $reportFullPath
    }

    $safeBatchName = $BatchName -replace '[^\w\-.]+', '-'
    $SummaryTxt = Join-Path $reportsFolder "lcc-summary-$safeBatchName.txt"
}

$summaryFullPath = Resolve-ToolkitPath -Path $SummaryTxt -ToolkitRoot $toolkitRoot
$summaryFolder = Split-Path -Parent $summaryFullPath

if ($summaryFolder -and -not (Test-Path $summaryFolder)) {
    New-Item -ItemType Directory -Force -Path $summaryFolder | Out-Null
}

$totalRows = $rows.Count

$matchedCount = Count-Where -Rows $rows -Predicate { $_.MatchStatus -eq "Matched" }
$noMatchCount = Count-Where -Rows $rows -Predicate { $_.MatchStatus -eq "No match" }
$multipleMatchCount = Count-Where -Rows $rows -Predicate {
    $_.MatchStatus -match "Multiple|Duplicate"
}
$otherMatchCount = $totalRows - $matchedCount - $noMatchCount - $multipleMatchCount

$wouldUpdateLccCount = Count-Where -Rows $rows -Predicate { $_.WouldUpdateLCC -eq "Yes" }
$wouldUpdatePrimaryCount = Count-Where -Rows $rows -Predicate { $_.WouldUpdateLCCPrimaryClass -eq "Yes" }
$wouldUpdateSecondaryCount = Count-Where -Rows $rows -Predicate { $_.WouldUpdateLCCSecondaryClass -eq "Yes" }
$wouldUpdatePathCount = Count-Where -Rows $rows -Predicate { $_.WouldUpdateLCCPath -eq "Yes" }

$warningRows = @($rows | Where-Object {
    $_.Warning -and -not [string]::IsNullOrWhiteSpace($_.Warning)
})

$warningCount = $warningRows.Count

$pendingUpdateTotal =
    $wouldUpdateLccCount +
    $wouldUpdatePrimaryCount +
    $wouldUpdateSecondaryCount +
    $wouldUpdatePathCount

$firstRow = $rows[0]

$hasConfidenceColumn =
    (Test-ColumnExists -Row $firstRow -ColumnName "LCCConfidence") -or
    (Test-ColumnExists -Row $firstRow -ColumnName "LCC Confidence")

$hasConfidenceStatusColumn = Test-ColumnExists -Row $firstRow -ColumnName "LCCConfidenceStatus"

$hasSourceNotesColumn =
    (Test-ColumnExists -Row $firstRow -ColumnName "LCCSourceNotes") -or
    (Test-ColumnExists -Row $firstRow -ColumnName "LCC Source Notes")

$hasManualReviewColumn = Test-ColumnExists -Row $firstRow -ColumnName "ManualReviewRequired"

$auditFieldsPresent =
    $hasConfidenceColumn -or
    $hasConfidenceStatusColumn -or
    $hasSourceNotesColumn -or
    $hasManualReviewColumn

$confidenceGroups = @()

if ($hasConfidenceColumn) {
    $confidenceGroups = @(
        $rows |
            Group-Object {
                Normalize-DisplayValue `
                    -Value (Get-RowValue -Row $_ -Names @("LCCConfidence", "LCC Confidence")) `
                    -BlankLabel "Unspecified"
            } |
            Sort-Object Name
    )
}
elseif ($hasConfidenceStatusColumn) {
    $confidenceGroups = @(
        $rows |
            Group-Object {
                Normalize-DisplayValue `
                    -Value (Get-RowValue -Row $_ -Names @("LCCConfidenceStatus")) `
                    -BlankLabel "Unspecified"
            } |
            Sort-Object Name
    )
}

$confidenceStatusGroups = @()

if ($hasConfidenceStatusColumn) {
    $confidenceStatusGroups = @(
        $rows |
            Group-Object {
                Normalize-DisplayValue `
                    -Value (Get-RowValue -Row $_ -Names @("LCCConfidenceStatus")) `
                    -BlankLabel "Unspecified"
            } |
            Sort-Object Name
    )
}

$manualReviewRows = @()

if ($hasManualReviewColumn) {
    $manualReviewRows = @(
        $rows | Where-Object {
            (Get-RowValue -Row $_ -Names @("ManualReviewRequired")) -eq "Yes"
        }
    )
}
elseif ($hasConfidenceColumn) {
    $manualReviewRows = @(
        $rows | Where-Object {
            (Get-RowValue -Row $_ -Names @("LCCConfidence", "LCC Confidence")) -eq "Low - Manual Review Recommended"
        }
    )
}

$manualReviewCount = $manualReviewRows.Count

$unexpectedConfidenceRows = @()

if ($hasConfidenceStatusColumn) {
    $unexpectedConfidenceRows = @(
        $rows | Where-Object {
            (Get-RowValue -Row $_ -Names @("LCCConfidenceStatus")) -eq "Unexpected"
        }
    )
}

$unexpectedConfidenceCount = $unexpectedConfidenceRows.Count

$sourceNotesCount = 0

if ($hasSourceNotesColumn) {
    $sourceNotesCount = Count-Where -Rows $rows -Predicate {
        $sourceNotes = Get-RowValue -Row $_ -Names @("LCCSourceNotes", "LCC Source Notes")
        -not [string]::IsNullOrWhiteSpace($sourceNotes)
    }
}

$status = "REVIEW REQUIRED"

$hasMatchProblems =
    $noMatchCount -gt 0 -or
    $multipleMatchCount -gt 0 -or
    $otherMatchCount -gt 0 -or
    $matchedCount -ne $totalRows

$hasAuditProblems =
    $manualReviewCount -gt 0 -or
    $unexpectedConfidenceCount -gt 0

$hasReviewProblems =
    $hasMatchProblems -or
    $warningCount -gt 0 -or
    $hasAuditProblems

if (
    $totalRows -gt 0 -and
    -not $hasReviewProblems -and
    $pendingUpdateTotal -eq 0
) {
    $status = "VERIFIED CLEAN"
}
elseif (
    $totalRows -gt 0 -and
    -not $hasReviewProblems -and
    $pendingUpdateTotal -gt 0
) {
    $status = "READY TO APPLY"
}

$lines = [System.Collections.Generic.List[string]]::new()

Add-Line -Lines $lines -Text "Calibre LCC Toolkit Batch Summary"
Add-Line -Lines $lines -Text "================================="
Add-Line -Lines $lines
Add-Line -Lines $lines -Text "Batch: $BatchName"
Add-Line -Lines $lines -Text "Report: $reportFullPath"
Add-Line -Lines $lines -Text "Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
Add-Line -Lines $lines
Add-Line -Lines $lines -Text "Rows"
Add-Line -Lines $lines -Text "----"
Add-Line -Lines $lines -Text "Total Rows:      $totalRows"
Add-Line -Lines $lines -Text "Matched:         $matchedCount"
Add-Line -Lines $lines -Text "No Match:        $noMatchCount"
Add-Line -Lines $lines -Text "Multiple Match:  $multipleMatchCount"
Add-Line -Lines $lines -Text "Other Status:    $otherMatchCount"
Add-Line -Lines $lines
Add-Line -Lines $lines -Text "Would Update"
Add-Line -Lines $lines -Text "------------"
Add-Line -Lines $lines -Text "LCC:                 $wouldUpdateLccCount"
Add-Line -Lines $lines -Text "Primary Class:       $wouldUpdatePrimaryCount"
Add-Line -Lines $lines -Text "Secondary Class:     $wouldUpdateSecondaryCount"
Add-Line -Lines $lines -Text "Classification Path: $wouldUpdatePathCount"
Add-Line -Lines $lines -Text "Total Field Updates: $pendingUpdateTotal"
Add-Line -Lines $lines
Add-Line -Lines $lines -Text "LCC Enrichment Audit"
Add-Line -Lines $lines -Text "--------------------"
Add-Line -Lines $lines -Text "Audit Fields Present: $auditFieldsPresent"
Add-Line -Lines $lines -Text "Manual Review Required Rows: $manualReviewCount"
Add-Line -Lines $lines -Text "Unexpected Confidence Rows:  $unexpectedConfidenceCount"
Add-Line -Lines $lines -Text "Rows With Source Notes:      $sourceNotesCount"

if ($hasConfidenceColumn -and $confidenceGroups.Count -gt 0) {
    Add-Line -Lines $lines
    Add-Line -Lines $lines -Text "LCC Confidence:"

    foreach ($group in $confidenceGroups) {
        Add-Line -Lines $lines -Text ("{0}: {1}" -f $group.Name, $group.Count)
    }
}
elseif ($hasConfidenceStatusColumn -and $confidenceGroups.Count -gt 0) {
    Add-Line -Lines $lines
    Add-Line -Lines $lines -Text "LCC Confidence:"

    foreach ($group in $confidenceGroups) {
        Add-Line -Lines $lines -Text ("{0}: {1}" -f $group.Name, $group.Count)
    }
}
else {
    Add-Line -Lines $lines
    Add-Line -Lines $lines -Text "LCC Confidence: Not provided"
}

if ($hasConfidenceStatusColumn -and $confidenceStatusGroups.Count -gt 0) {
    Add-Line -Lines $lines
    Add-Line -Lines $lines -Text "LCC Confidence Status:"

    foreach ($group in $confidenceStatusGroups) {
        Add-Line -Lines $lines -Text ("{0}: {1}" -f $group.Name, $group.Count)
    }
}

if ($manualReviewCount -gt 0) {
    Add-Line -Lines $lines
    Add-Line -Lines $lines -Text "Manual Review Details:"
    foreach ($manualReviewRow in $manualReviewRows | Select-Object -First 20) {
        $confidenceValue = Get-RowValue -Row $manualReviewRow -Names @("LCCConfidence", "LCC Confidence")
        $sourceNotes = Get-RowValue -Row $manualReviewRow -Names @("LCCSourceNotes", "LCC Source Notes")

        if ([string]::IsNullOrWhiteSpace($confidenceValue)) {
            $confidenceValue = "Unspecified"
        }

        Add-Line -Lines $lines -Text "- $($manualReviewRow.InputTitle) [$($manualReviewRow.ISBN)]: $confidenceValue"

        if (-not [string]::IsNullOrWhiteSpace($sourceNotes)) {
            Add-Line -Lines $lines -Text "  Source Notes: $sourceNotes"
        }
    }

    if ($manualReviewCount -gt 20) {
        Add-Line -Lines $lines -Text "- Additional manual review rows omitted from summary. See CSV report."
    }
}

if ($unexpectedConfidenceCount -gt 0) {
    Add-Line -Lines $lines
    Add-Line -Lines $lines -Text "Unexpected Confidence Details:"
    foreach ($unexpectedRow in $unexpectedConfidenceRows | Select-Object -First 20) {
        $confidenceValue = Get-RowValue -Row $unexpectedRow -Names @("LCCConfidence", "LCC Confidence")
        Add-Line -Lines $lines -Text "- $($unexpectedRow.InputTitle) [$($unexpectedRow.ISBN)]: $confidenceValue"
    }

    if ($unexpectedConfidenceCount -gt 20) {
        Add-Line -Lines $lines -Text "- Additional unexpected confidence rows omitted from summary. See CSV report."
    }
}

Add-Line -Lines $lines
Add-Line -Lines $lines -Text "Warnings"
Add-Line -Lines $lines -Text "--------"
Add-Line -Lines $lines -Text "Warning Rows: $warningCount"

if ($warningCount -gt 0) {
    Add-Line -Lines $lines
    Add-Line -Lines $lines -Text "Warning Details:"
    foreach ($warningRow in $warningRows | Select-Object -First 20) {
        Add-Line -Lines $lines -Text "- $($warningRow.InputTitle) [$($warningRow.ISBN)]: $($warningRow.Warning)"
    }

    if ($warningCount -gt 20) {
        Add-Line -Lines $lines -Text "- Additional warnings omitted from summary. See CSV report."
    }
}

Add-Line -Lines $lines
Add-Line -Lines $lines -Text "Status"
Add-Line -Lines $lines -Text "------"
Add-Line -Lines $lines -Text $status

$lines | Set-Content -Path $summaryFullPath -Encoding UTF8

Write-Host ""
Write-Host "Summary written to: $summaryFullPath"
Write-Host ""
Write-Host "Batch: $BatchName"
Write-Host "Rows: $totalRows"
Write-Host "Matched: $matchedCount"
Write-Host "Pending field updates: $pendingUpdateTotal"
Write-Host "Warnings: $warningCount"
Write-Host "Manual review required: $manualReviewCount"
Write-Host "Unexpected confidence: $unexpectedConfidenceCount"
Write-Host "Status: $status"