<#
.SYNOPSIS
Writes a concise summary report for a Calibre LCC dry-run or verification CSV.

.DESCRIPTION
Reads a report generated by Test-LccImportDryRun.ps1 and writes a human-readable
summary text file showing match counts, pending update counts, warnings, and final
batch status.

This script does not modify Calibre metadata.

.EXAMPLE
powershell -ExecutionPolicy Bypass -File .\scripts\Write-LccBatchSummary.ps1 `
  -ReportCsv ".\reports\lcc-dryrun-herbert-baxter-adams-v02-test.csv" `
  -SummaryTxt ".\reports\lcc-summary-herbert-baxter-adams-v02-test.txt" `
  -BatchName "herbert-baxter-adams-v02-test"
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$ReportCsv,

    [string]$SummaryTxt = "",

    [string]$BatchName = "",

    [string]$ConfigPath = ".\config\lcc-toolkit.config.json"
)

function Get-ToolkitRoot {
    $scriptFolder = Split-Path -Parent $PSCommandPath
    return Split-Path -Parent $scriptFolder
}

function Resolve-ToolkitPath {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,

        [Parameter(Mandatory = $true)]
        [string]$ToolkitRoot
    )

    if ([System.IO.Path]::IsPathRooted($Path)) {
        return $Path
    }

    return Join-Path $ToolkitRoot $Path
}

function Count-Where {
    param(
        [Parameter(Mandatory = $true)]
        [object[]]$Rows,

        [Parameter(Mandatory = $true)]
        [scriptblock]$Predicate
    )

    return @($Rows | Where-Object $Predicate).Count
}

function Add-Line {
    param(
        [System.Collections.Generic.List[string]]$Lines,

        [string]$Text = ""
    )

    $Lines.Add($Text) | Out-Null
}

$toolkitRoot = Get-ToolkitRoot

$configFullPath = Resolve-ToolkitPath -Path $ConfigPath -ToolkitRoot $toolkitRoot

if (Test-Path $configFullPath) {
    $config = Get-Content $configFullPath -Raw | ConvertFrom-Json
}
else {
    $config = $null
}

$reportFullPath = Resolve-ToolkitPath -Path $ReportCsv -ToolkitRoot $toolkitRoot

if (-not (Test-Path $reportFullPath)) {
    throw "Report CSV not found: $reportFullPath"
}

$rows = @(Import-Csv $reportFullPath)

if ($rows.Count -eq 0) {
    throw "Report CSV contains no rows: $reportFullPath"
}

if ([string]::IsNullOrWhiteSpace($BatchName)) {
    $BatchName = [System.IO.Path]::GetFileNameWithoutExtension($reportFullPath)
}

if ([string]::IsNullOrWhiteSpace($SummaryTxt)) {
    if ($null -ne $config -and -not [string]::IsNullOrWhiteSpace($config.ReportsFolder)) {
        $reportsFolder = Resolve-ToolkitPath -Path $config.ReportsFolder -ToolkitRoot $toolkitRoot
    }
    else {
        $reportsFolder = Split-Path -Parent $reportFullPath
    }

    $safeBatchName = $BatchName -replace '[^\w\-.]+', '-'
    $SummaryTxt = Join-Path $reportsFolder "lcc-summary-$safeBatchName.txt"
}

$summaryFullPath = Resolve-ToolkitPath -Path $SummaryTxt -ToolkitRoot $toolkitRoot
$summaryFolder = Split-Path -Parent $summaryFullPath

if ($summaryFolder -and -not (Test-Path $summaryFolder)) {
    New-Item -ItemType Directory -Force -Path $summaryFolder | Out-Null
}

$totalRows = $rows.Count

$matchedCount = Count-Where -Rows $rows -Predicate { $_.MatchStatus -eq "Matched" }
$noMatchCount = Count-Where -Rows $rows -Predicate { $_.MatchStatus -eq "No match" }
$multipleMatchCount = Count-Where -Rows $rows -Predicate {
    $_.MatchStatus -match "Multiple|Duplicate"
}
$otherMatchCount = $totalRows - $matchedCount - $noMatchCount - $multipleMatchCount

$wouldUpdateLccCount = Count-Where -Rows $rows -Predicate { $_.WouldUpdateLCC -eq "Yes" }
$wouldUpdatePrimaryCount = Count-Where -Rows $rows -Predicate { $_.WouldUpdateLCCPrimaryClass -eq "Yes" }
$wouldUpdateSecondaryCount = Count-Where -Rows $rows -Predicate { $_.WouldUpdateLCCSecondaryClass -eq "Yes" }
$wouldUpdatePathCount = Count-Where -Rows $rows -Predicate { $_.WouldUpdateLCCPath -eq "Yes" }

$warningRows = @($rows | Where-Object {
    $_.Warning -and -not [string]::IsNullOrWhiteSpace($_.Warning)
})

$warningCount = $warningRows.Count

$pendingUpdateTotal =
    $wouldUpdateLccCount +
    $wouldUpdatePrimaryCount +
    $wouldUpdateSecondaryCount +
    $wouldUpdatePathCount

$status = "NEEDS REVIEW"

if (
    $totalRows -gt 0 -and
    $matchedCount -eq $totalRows -and
    $pendingUpdateTotal -eq 0 -and
    $warningCount -eq 0
) {
    $status = "VERIFIED CLEAN"
}
elseif (
    $matchedCount -eq $totalRows -and
    $pendingUpdateTotal -gt 0 -and
    $warningCount -eq 0
) {
    $status = "READY TO APPLY"
}

$lines = [System.Collections.Generic.List[string]]::new()

Add-Line -Lines $lines -Text "Calibre LCC Toolkit Batch Summary"
Add-Line -Lines $lines -Text "================================="
Add-Line -Lines $lines
Add-Line -Lines $lines -Text "Batch: $BatchName"
Add-Line -Lines $lines -Text "Report: $reportFullPath"
Add-Line -Lines $lines -Text "Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
Add-Line -Lines $lines
Add-Line -Lines $lines -Text "Rows"
Add-Line -Lines $lines -Text "----"
Add-Line -Lines $lines -Text "Total Rows:      $totalRows"
Add-Line -Lines $lines -Text "Matched:         $matchedCount"
Add-Line -Lines $lines -Text "No Match:        $noMatchCount"
Add-Line -Lines $lines -Text "Multiple Match:  $multipleMatchCount"
Add-Line -Lines $lines -Text "Other Status:    $otherMatchCount"
Add-Line -Lines $lines
Add-Line -Lines $lines -Text "Would Update"
Add-Line -Lines $lines -Text "------------"
Add-Line -Lines $lines -Text "LCC:                 $wouldUpdateLccCount"
Add-Line -Lines $lines -Text "Primary Class:       $wouldUpdatePrimaryCount"
Add-Line -Lines $lines -Text "Secondary Class:     $wouldUpdateSecondaryCount"
Add-Line -Lines $lines -Text "Classification Path: $wouldUpdatePathCount"
Add-Line -Lines $lines -Text "Total Field Updates: $pendingUpdateTotal"
Add-Line -Lines $lines
Add-Line -Lines $lines -Text "Warnings"
Add-Line -Lines $lines -Text "--------"
Add-Line -Lines $lines -Text "Warning Rows: $warningCount"

if ($warningCount -gt 0) {
    Add-Line -Lines $lines
    Add-Line -Lines $lines -Text "Warning Details:"
    foreach ($warningRow in $warningRows | Select-Object -First 20) {
        Add-Line -Lines $lines -Text "- $($warningRow.InputTitle) [$($warningRow.ISBN)]: $($warningRow.Warning)"
    }

    if ($warningCount -gt 20) {
        Add-Line -Lines $lines -Text "- Additional warnings omitted from summary. See CSV report."
    }
}

Add-Line -Lines $lines
Add-Line -Lines $lines -Text "Status"
Add-Line -Lines $lines -Text "------"
Add-Line -Lines $lines -Text $status

$lines | Set-Content -Path $summaryFullPath -Encoding UTF8

Write-Host ""
Write-Host "Summary written to: $summaryFullPath"
Write-Host ""
Write-Host "Batch: $BatchName"
Write-Host "Rows: $totalRows"
Write-Host "Matched: $matchedCount"
Write-Host "Pending field updates: $pendingUpdateTotal"
Write-Host "Warnings: $warningCount"
Write-Host "Status: $status"
